---
root: true
env:
  es6: true
  node: true
  mocha: true
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:react/recommended
parser: babel-eslint
plugins:
  - babel
  - flowtype
  - html
  - import
  - json
  - markdown
  - react
parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
    experimentalObjectRestSpread: true
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  default-case:
    - error
  eqeqeq:
    - error
    - always
  no-empty:
    - error
  no-empty-function:
    - error
  no-eval:
    - error
  no-fallthrough:
    - warn
  no-lone-blocks:
    - error
  no-loop-func:
    - error
  no-multi-spaces:
    - error
  no-multi-str:
    - error
  no-param-reassign:
    - error
  no-self-compare:
    - error
  no-useless-escape:
    - error
  no-useless-concat:
    - error
  no-with:
    - error
  yoda:
    - error
  no-unused-vars:
    - warn
  no-use-before-define:
    - error
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    -
      before: false
      after: true
  eol-last:
    - error
  no-trailing-spaces:
    - error

# eslint-plugin-babel rules:
  arrow-body-style:
    - error
    - as-needed
  arrow-spacing:
    - error
    -
      before: true
      after: true
  generator-star-spacing:
    - error
    -
      before: false
      after: true
  no-confusing-arrow:
    - error
    -
      allowParens: true
  no-duplicate-imports:
    - error
  no-var:
    - error
  object-shorthand:
    - error
  prefer-arrow-callback:
    - error
    -
      allowNamedFunctions: true
  prefer-const:
    - error
  prefer-rest-params:
    - error
  prefer-spread:
    - error
  prefer-template:
    - error
  rest-spread-spacing:
    - error
    - never
  template-curly-spacing:
    - error
  yield-star-spacing:
    - error
    - after
