---
root: true
extends:
  - eslint:recommended
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  eol-last:
    - error
  no-trailing-spaces:
    - error
